//constants
export const CONST = {
    TEXT: "text",
    MAP: "map",
    MAPDATA: "mapdata",
    MUSIC: "music",
    MIDI: "midi",
    MP3: "mp3",
    PNG: "png",
    MUS: "mus",
    GRAPHIC: "graphic",
    FLAT: "flat",
    MARKER: "marker",
    PLAYPAL: "PLAYPAL",
    COLORMAP: "COLORMAP",
    ENDOOM: "ENDOOM",
    PNAMES: "PNAMES",
    TEXTUREx: ["TEXTURE1", "TEXTURE2"],
    GRAPHIC_MARKERS: [
        "P_",
        "PP_",
        "P1_",
        "P2_",
        "P3_",
        "S_",
        "S2_",
        "S3_",
        "SS_"
    ],
    FLAT_MARKERS: ["F_", "FF_", "F1_", "F2_", "F3_"],
    MAPLUMPS: [
        "THINGS",
        "LINEDEFS",
        "SIDEDEFS",
        "VERTEXES",
        "SEGS",
        "TEXTMAP",
        "SSECTORS",
        "NODES",
        "SECTORS",
        "REJECT",
        "BLOCKMAP",
        "BEHAVIOR",
        "ZNODES"
    ],
    TEXTLUMPS: [
        "DEHACKED",
        "MAPINFO",
        "ZMAPINFO",
        "EMAPINFO",
        "DMXGUS",
        "DMXGUSC",
        "WADINFO",
        "EMENUS",
        "MUSINFO",
        "SNDINFO",
        "GLDEFS",
        "KEYCONF",
        "SCRIPTS",
        "LANGUAGE",
        "DECORATE",
        "SBARINFO",
        "MENUDEF"
    ],
    DATA_LUMPS: [
        "PLAYPAL",
        "COLORMAP",
        "TEXTURE1",
        "TEXTURE2",
        "PNAMES",
        "ENDOOM"
    ],
    DEFAULT_EXTENSION: "lmp",
    EXTENSIONS: {
        text: "txt",
        mp3: "mp3",
        mus: "mus",
        midi: "mid",
        png: "png"
    }
};
